MyProjectSAD/Models/AppModel.cs
namespace MyProjectSAD.Models
{
    
        public class RoleAssignment
        {
            public string Id { get; set; }
            public string Name { get; set; }
            public bool IsChecked { get; set; }
        }
        public class UserRoleViewModel
        {
            public string UserId { get; set; }
            public string UserName { get; set; }
            public List<RoleAssignment> UserRoles { get; set; }

            public UserRoleViewModel()
            {
                this.UserRoles = new List<RoleAssignment>();
            }
        }
    }

MyProjectSAD/Models/Author.cs
using System.ComponentModel.DataAnnotations;

namespace MyProjectSAD.Models
{
    public class Author
    {
        [Key]
        public int AuthorId {  get; set; }
        public string AuthorFname {  get; set; }
        public string AuthorLname {  get; set; }

    }
}

MyProjectSAD/Models/ErrorViewModel.cs
namespace MyProjectSAD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyProjectSAD/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MyProjectSAD.Models;

namespace MyProjectSAD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyProjectSAD/Controllers/RolesAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using MyProjectSAD.Models;
using MyProjectSAD.Data;
using Microsoft.AspNetCore.Authorization;


namespace MyProjectSAD.Controllers
{
    
    public class RolesAdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesAdminController(ApplicationDbContext context,
UserManager<IdentityUser> userManager, RoleManager<IdentityRole>
roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var roles = _context.Roles.OrderBy(r => r.Name).ToList();
            //select Name from Roles Order by Names;
            return View(roles);
        }
        public IActionResult ListUsers()
        {
            var users = _context.Users.OrderBy(u => u.UserName).ToList();
            //Select UserName from Users Order By UserName
            return View(users);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(IFormCollection collection)
        {
            IdentityResult ir = new IdentityResult();
            var _role = new IdentityRole();
            _role.Name = collection["RoleName"];
            ir = await _roleManager.CreateAsync(_role);
            if (!ir.Succeeded)
            {
                foreach (IdentityError er in ir.Errors)
                {
                    ModelState.AddModelError(string.Empty,
                   er.Description);
                }
                ViewBag.UserMessage = "Error Addding Role";
                return View();
            }
            else
            {
                ViewBag.UserMessage = "Role Added";
                return RedirectToAction(nameof(Index));
            }
        }
        [HttpPost]
        public async Task<IActionResult> ManageUserRoles(IFormCollection form)
        {
            UserRoleViewModel vm = new UserRoleViewModel();
            var username = form["UserName"];
            var user = _context.Users.Where(u => u.UserName == username.ToString()).FirstOrDefault();
            if (user != null)
            {
                var roles = _context.Roles.ToList();
                vm.UserName = username;
                vm.UserId = user.Id;
                foreach (var item in roles)
                {
                    RoleAssignment roleAssigned = new RoleAssignment();
                    roleAssigned.Name = item.Name;
                    roleAssigned.Id = item.Id;

                    if (await _userManager.IsInRoleAsync(user, item.Name))
                    {
                        roleAssigned.IsChecked = true;
                    }
                    else
                    {
                        roleAssigned.IsChecked = false;
                    }
                    vm.UserRoles.Add(roleAssigned);
                }
            }
            else
            {
                vm = null;
            }

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateRoles(UserRoleViewModel updateRoles, IFormCollection form)
        {
            var user = _context.Users.Where(u => u.UserName ==
           form["UserName"].ToString()).FirstOrDefault();
            foreach (var item in updateRoles.UserRoles)
            {
                if (item.IsChecked)
                {
                    if (!await _userManager.IsInRoleAsync(user, item.Name))
                    {
                        await _userManager.AddToRoleAsync(user, item.Name);

                    }
                }
                else if (await _userManager.IsInRoleAsync(user, item.Name))
                {
                    await _userManager.RemoveFromRoleAsync(user,
                   item.Name);
                }
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

MyProjectSAD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyProjectSAD/Views/RolesAdmin/Create.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
<h2>Add Role</h2>
@if (ViewBag.UserMessage != null)
{
	<h2>@ViewBag.UserMessage</h2>
}
<form asp-controller="RolesAdmin" asp-action="Create">
	<div>
		Role Name
	</div>
	<p>
		@Html.TextBox("RoleName")
	</p>
	<input type="submit" class="btn btn-primary" value="Save" />
</form>

MyProjectSAD/Views/RolesAdmin/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
<h1>Roles Admin</h1>
<table class="table table-striped">
	<tr>
		<td>Existing Roles in the System</td>
	</tr>
	@foreach (var item in Model)
	{
		<tr>
			<td>@item.Name</td>
		</tr>

	}

</table>
@Html.ActionLink("Create New Role", "Create", "RolesAdmin", 
routeValues: null, htmlAttributes: new { @class = "btn btn-primary", 
@role="button" })
<hr />
<div class="panel panel-info">
 <div class="panel-heading">
 Search User
 </div>
 <div class="panel-body">
 <div class="row">
 <div class="col-md-6">
 
@using(Html.BeginForm("ManageUserRoles","RolesAdmin"))
 {
 <div class="form-inline">
 @Html.TextArea("UserName")
 </div>
 <div class="form-inline">
 <input type="submit" value="Search"
class="btn btn-primary" />
 </div> 
 }
 </div>
 <div class="col-md-6">
 @Html.ActionLink("or List All Users", "ListUsers", 
"RolesAdmin", routeValues: null, htmlAttributes: new { @class = "btn btn-success", @role="button" })
 </div>
 </div>
 </div>
</div>

MyProjectSAD/Views/RolesAdmin/ListUsers.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>
<h2>List of Users</h2>
<hr />
<table class="table table-striped">
 <tr>
 <th>Email</th>
 <th></th>
 <th></th>
 </tr>
 @foreach(var item in Model)
 {
 <tr>
 <td>@item.UserName</td>
 <td>
 <form
action="@Url.Action("ManageUserRoles","RolesAdmin")" method="post"
class="form-inline">
 <input type="hidden" id="UserName" name="UserName" value="@item.UserName"/>
 <input type="submit" class="btn btn-primary" value="Manage Roles"/>
 </form>
 </td>
 <td>
 @Html.ActionLink("ResetPassword","resetpassword",new{id=item.Id},new{@class="btn btn-primary"})
 </td>
 </tr>
 }
</table>

MyProjectSAD/Views/RolesAdmin/ManageUserRoles.cshtml
@model MyProjectSAD.Models.UserRoleViewModel
<h2>Manage Roles</h2>
@if(Model!=null)
{
 <div class="panel panel-info">
 <div class="panel-heading">
 <div class="row">
 <div class="col-md-8">
 <h3>@Model.UserName</h3>
 </div>
			</div>
		</div>
		<div class="panel-body">
			<form asp-controller="RolesAdmin" asp-action="UpdateRoles" class="form" method="post">
				@Html.HiddenFor(m => m.UserId)
				@Html.HiddenFor(m => m.UserName)
				@for (int i = 0; i < Model.UserRoles.Count; i++)
				{
					<div class="checkbox" style="padding-left:25px">

						@Html.CheckBoxFor(m => m.UserRoles[i].IsChecked, new
							{ id = "userRoles_" + i })
						@Html.HiddenFor(m => m.UserRoles[i].Id)
						@Html.HiddenFor(m => m.UserRoles[i].Name)
						@Html.DisplayFor(m => m.UserRoles[i].Name)
					</div>
				}
				<input type="submit" value="Submit" class="btn btnprimary" />
			</form>
		</div>
	</div>
}
else
{
	<h3>User not found</h3>
	@Html.ActionLink("Back to Roles Admin", "Index", null, new
		{ @class = "btn btn-primary" })
}

MyProjectSAD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyProjectSAD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyProjectSAD.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyProjectSAD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MyProjectSAD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>